lib/renaissance_web/router.ex
defmodule RenaissanceWeb.Router do
  use RenaissanceWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug Phoenix.LiveView.Flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :put_layout, {RenaissanceWeb.LayoutView, :app}
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", RenaissanceWeb do
    pipe_through :browser

    get "/", AuctionController, :index
    get "/login", LoginController, :login
    post "/login", LoginController, :verify

    resources "/register", RegisterController, only: [:new, :create]
    resources "/auctions", AuctionController, only: [:index, :create, :new, :show, :update]
    resources "/bids", BidController, only: [:create]
  end
end

lib/renaissance/auctions/auction.ex
defmodule Renaissance.Auction do
  use Ecto.Schema
  import Ecto.Changeset
  alias Renaissance.{User, Bid}
  alias Renaissance.Helpers.Validators

  @required_fields ~w(title description seller_id starting_amount end_auction_at)a
  @optional_fields ~w()a

  schema "auctions" do
    field :title, :string
    field :description, :string
    field :starting_amount, Money.Ecto.Amount.Type
    field :end_auction_at, :utc_datetime
    belongs_to :seller, User
    has_many :bids, Bid
    has_one :highest_bid, Bid

    timestamps(type: :utc_datetime)
  end

  @doc false
  def changeset(auction, attrs \\ %{}) do
    auction
    |> cast(attrs, @required_fields ++ @optional_fields)
    |> validate_required(@required_fields)
    |> foreign_key_constraint(:seller_id, name: :auctions_user_id_fkey)
    |> Validators.validate_starting_amount()
    |> validate_end_datetime()
  end

  defp validate_end_datetime(changeset) do
    end_at = get_change(changeset, :end_auction_at)

    if DateTime.compare(DateTime.utc_now(), end_at || DateTime.utc_now()) == :lt do
      changeset
    else
      add_error(changeset, :end_auction_at, "should be in the future")
    end
  end
end

lib/renaissance/auctions/auctions.ex
defmodule Renaissance.Auctions do
  import Ecto.{Query, Changeset}
  alias Renaissance.{Auction, Bid, Helpers, Repo}

  def insert(params) do
    params = Helpers.Money.to_money!(params, "starting_amount")
    Auction.changeset(%Auction{}, params) |> Repo.insert()
  end

  def exists?(nil), do: false

  def exists?(id) do
    Repo.exists?(from(a in Auction, where: a.id == ^id))
  end

  def update(id, params) do
    auction = get!(id)

    args = %{
      description: params["description"] || auction.description,
      title: params["title"] || auction.title
    }

    change(auction, args) |> Repo.update()
  end

  def get!(nil), do: nil

  def get!(id) do
    Auction
    |> preload(:seller)
    |> preload(highest_bid: ^Bid.highest())
    |> Repo.get!(id)
  end

  def get_all() do
    Auction
    |> preload(:seller)
    |> preload(highest_bid: ^Bid.highest())
    |> order_by(asc: :end_auction_at, asc: :inserted_at)
    |> Repo.all()
  end

  def open?(id) do
    case Repo.get(Auction, id) do
      nil -> false
      auction -> Timex.after?(auction.end_auction_at, Timex.now())
    end
  end

  def get_detailed(id) do
    auction = get!(id)
    amount = extract_current_amount(auction)
    Map.put(auction, :current_amount, amount)
  end

  def get_all_detailed do
    for auction <- get_all() do
      Map.put(auction, :current_amount, extract_current_amount(auction))
    end
  end

  defp extract_current_amount(auction) do
    case auction.highest_bid do
      nil -> auction.starting_amount
      bid -> bid.amount
    end
    |> Helpers.Money.to_money()
  end
end

lib/renaissance_web/controllers/auction_controller.ex
defmodule RenaissanceWeb.AuctionController do
  use RenaissanceWeb, :controller

  alias Renaissance.{Auction, Auctions}
  alias RenaissanceWeb.Helpers.Auth

  def index(conn, _params) do
    if Auth.signed_in?(conn) do
      render(conn, "index.html", auctions: Auctions.get_all_detailed())
    else
      redirect(conn, to: Routes.login_path(conn, :login))
    end
  end

  def new(conn, _params) do
    changeset = Auction.changeset(%Auction{})

    if Auth.signed_in?(conn) do
      render(conn, "new.html", changeset: changeset)
    else
      redirect(conn, to: Routes.login_path(conn, :login))
    end
  end

  def create(conn, %{"auction" => auction}) do
    seller_id = Auth.current_user(conn).id
    params = Map.put(auction, "seller_id", seller_id)

    case Auctions.insert(params) do
      {:ok, _user} ->
        conn
        |> put_flash(:info, "Auction Created!")
        |> redirect(to: Routes.auction_path(conn, :index))

      {:error, changeset} ->
        render(conn, "create.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    if Auth.signed_in?(conn) do
      id = String.to_integer(id)

      render(conn, "show.html", %{
        auction: Auctions.get_detailed(id),
        user: Auth.current_user(conn),
        changeset: conn
      })
    else
      redirect(conn, to: Routes.login_path(conn, :login))
    end
  end

  def update(conn, params) do
    id = String.to_integer(params["id"])

    with {:ok, _auctions} <- Auctions.update(id, params) do
      conn
      |> put_flash(:info, "Auction Updated!")
      |> render("show.html", %{
        auction: Auctions.get_detailed(id),
        user: Auth.current_user(conn),
        changeset: conn
      })
    else
      {:error, changeset} ->
        render(conn, "show.html", changeset: changeset)
    end
  end
end

lib/renaissance_web/views/auction_view.ex
defmodule RenaissanceWeb.AuctionView do
  use RenaissanceWeb, :view
  alias Renaissance.Helpers

  def default_end do
    current = DateTime.utc_now()

    %{
      day: current.day,
      hour: current.hour,
      minute: current.minute,
      month: current.month,
      year: current.year
    }
  end

  def float_amount(amount), do: Helpers.Money.to_float(amount)
end

lib/renaissance_web/templates/auction/_auction.html.eex
<a class="auction-container" href="<%= Routes.auction_path(@conn, :show, @auction) %>">
  <h4 class="auction-title"><%= @auction.title %></h4>
  <p class="auction-description"><%= @auction.description %></p>
  <li>Price: <%= @auction.current_amount %></li>
  <li>Seller: <%= @auction.seller.email %></li>
  <li>End Date: <%= @auction.end_auction_at %></li>
</a>

lib/renaissance_web/templates/auction/_details.html.eex
<div class="mod-table">
  <table class="item-table">
    <tr>
      <td class="table-left">Price:</td>
      <td class="bold table-right"><%= @auction.current_amount %></td>
    </tr>
    <tr>
      <td class="table-left">Seller:</td>
      <td class="bold table-right"> <%= @auction.seller.email %></td>
    </tr>
    <tr>
      <td class="table-left">End Date:</td>
      <td class="bold table-right"><%= @auction.end_auction_at %></td>
    </tr>
  </table>
</div>

lib/renaissance_web/templates/auction/auction_list.html.eex
<div class="pageContent">
  <div class="pageGroup">
    <h1 class="lbl-group">Auctions</h1>
    <div class="content-text">
        <a href="<%= Routes.auction_path(@conn, :new) %>">Start an Auction</a>
    </div>
    <%= for auction <- @auctions do %>
      <%= render("single_auction.html", auction: auction) %>
    <% end %>
  </div>
</div>

lib/renaissance_web/templates/auction/create.html.eex
  <div class="pageContent">
  <div class="pageGroup">
    <h1 class="lbl-group">Create an Auction</h1>

    <%= form_for @changeset, Routes.auction_path(@conn, :create), fn f -> %>
    <div class="form-section">
      <%= label f, :title, class: "lbl-form" %>
      <%= text_input f, :title,  class: "txt-form",
      placeholder: "Auction Title", required: true %>
      <%= error_tag f, :title %>
    </div>

    <div class="form-section">
      <%= label f, :description, class: "lbl-form" %>
      <%= text_input f, :description, class: "txt-form",
      placeholder: "Item Description", required: true %>
      <%= error_tag f, :description %>
    </div>

    <div class="form-section form-section-horizontal">
      <div class="form-section-half half-left">
        <%= label f, :starting_amount, "Starting Price", class: "lbl-form" %>
        <div class="form-section-horizontal">
          <p class="dollar-sign">$</p>
          <%= number_input f, :starting_amount,  class: "txt-form",
          required: true, min: 0.01, step: 0.01, value: 0.01 %>
        </div>
        <%= error_tag f, :starting_amount %>
      </div>


      <div class="form-section-half half-right">
        <%= label f, :end_auction_at, "End Date and Time (UTC)", class: "lbl-form" %>
        <div class="form-multi-input">
          <%= datetime_select f, :end_auction_at, required: true,
          class: "form-control", year: [options: 2019..2030],
          default: default_end() %>
        </div>
        <%= error_tag f, :end_auction_at %>
      </div>
    </div>
    <div class="nav-container">
      <div class="nav-spacer"></div>
      <%= submit "Create Auction"%>
    </div>
  </div>
  <% end %>
</div>

lib/renaissance_web/templates/auction/index.html.eex
<div class="pageContent">
  <div class="pageGroup">
    <h1 class="lbl-group">Auctions</h1>
    <div class="content-text">
      <%= link("Start an Auction", to: Routes.auction_path(@conn, :new)) %>
    </div>
    <%= if Enum.count(Auctions.get_won_auctions(RenaissanceWeb.Helpers.Auth.current_user(@conn).id)) > 0 do %>
      <div class="content-text">
        <%= link("View Purchases", to: Routes.purchase_path(@conn, :index)) %>
      </div>
    <% end %>
    <%= render_many @auctions, RenaissanceWeb.AuctionView, "_auction.html", conn: @conn %>
  </div>
</div>

lib/renaissance_web/templates/auction/new.html.eex
<%= render "create.html", Map.put(assigns, :action, Routes.auction_path(@conn, :create)) %>

lib/renaissance_web/templates/auction/new_auction.html.eex
<div class="pageContent">
  <div class="pageGroup">
    <h1 class="lbl-group">Create an Auction</h1>
    <%= form_for @changeset, Routes.auction_path(@conn, :create), fn f -> %>
  
      <div class="form-section">
        <%= label f, :title, class: "lbl-form" %>
        <%= text_input f, :title,  class: "txt-form", placeholder: "Auction Title", required: true %>
        <%= error_tag f, :title %>
      </div>

      <div class="form-section">
          <%= label f, :description, class: "lbl-form" %>
          <%= text_input f, :description, class: "txt-form", placeholder: "Item Description", required: true %>
          <%= error_tag f, :description %>
        </div>

      <div class="form-section form-section-horizontal">
        <div class="form-section-half half-left">
            <%= label f, "Price", class: "lbl-form" %>
            <div class="form-section-horizontal">
              <p class="dollar-sign">$</p>
              <%= number_input f, :price,  class: "txt-form", required: true, min: 1.00, step: 0.01, value: 1.00 %>
            </div>
            <%= error_tag f, :price %>
        </div>
        <div class="form-section-half half-right">
            <%= label f, "End Date and Time", class: "lbl-form" %>
            <div class="form-multi-input">
              <%= date_input f, :end_date_day,  class: "date-form half-left", placeholder: "Item Description", required: true %>
              <%= time_input f, :end_date_time,  class: "date-form half-right", placeholder: "Item Description", required: true %>
            </div>
            <%= error_tag f, :end_date %>
          </div>
      </div>
  
      <div class="form-section">
        <%= submit "Create Auction" %>
      </div>
    <% end %>
  </div>
</div>

lib/renaissance_web/templates/auction/show.html.eex
  <div class="pageContent">
  <div class="pageGroup">
  <%= if @user.email != @auction.seller.email do %>
    <h1 class="lbl-group"><%= @auction.title %></h1>
    <h4 class="mod-txt_secondary"><%= @auction.description %></h4>
    <%= render("_details.html", auction: @auction) %>
    <%= form_for @changeset, Routes.bid_path(@conn, :create), fn f -> %>
      <div class="form-section">
        <%= hidden_input f, :auction_id, value: @auction.id%>
        <%= label f, :amount, "Make a Bid", class: "lbl-form" %>
        <div class="form-section-horizontal">
          <p class="dollar-sign">$</p>
          <%= number_input f, :amount, class: "txt-form",
          required: true, min: float_amount(@auction.current_amount),
          step: 0.01, value: float_amount(@auction.current_amount) + 1.00 %>
        </div>
        <%= error_tag f, :amount %>
      </div>
    <%= live_render(@conn, RenaissanceWeb.AuctionsLive.Show, session: %{auction: @auction}) %>
    <div class="nav-container">
      <%= link "back", to: Routes.auction_path(@conn, :index), class: "button" %>
      <div class="nav-spacer"></div>
      <%= submit "Submit Bid" %>
    </div>
    <% end %>
  <% else %>
    <%= form_for @changeset, Routes.auction_path(@conn, :update, @auction), [method: :put], fn f -> %>
      <%= text_input f, :title, class: "edit-title auction-editable lbl-group",
      value: @auction.title, title: "Click here to edit the auction title.",required: true %>
      <%= error_tag f, :title %>

      <%= text_input f, :description, class: "mod-txt_secondary edit-description auction-editable",
      value: @auction.description, title: "Click here to edit the auction description.", required: true %>
      <%= error_tag f, :description %>
      <%= render("_details.html", auction: @auction) %>
      <%= live_render(@conn, RenaissanceWeb.AuctionsLive.Show, session: %{auction: @auction}) %>
      <div class="nav-container">
        <%= link "back", to: Routes.auction_path(@conn, :index), class: "button" %>
        <div class="nav-spacer"></div>
        <%= submit "Update Auction" %>
      </div>
    <% end %>
  <% end %>
  </div>
</div>