lib/renaissance_web/router.ex
defmodule RenaissanceWeb.Router do
  use RenaissanceWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug Phoenix.LiveView.Flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :put_layout, {RenaissanceWeb.LayoutView, :app}
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", RenaissanceWeb do
    pipe_through :browser

    get "/", AuctionController, :index
    get "/login", LoginController, :login
    post "/login", LoginController, :verify

    resources "/register", RegisterController, only: [:new, :create]
    resources "/auctions", AuctionController, only: [:index, :create, :new, :show, :update]
    resources "/bids", BidController, only: [:create]
  end
end

lib/renaissance_web/controllers/login_controller.ex
defmodule RenaissanceWeb.LoginController do
  use RenaissanceWeb, :controller
  alias Renaissance.{User, Users}
  alias RenaissanceWeb.Helpers.{Auth}

  def login(conn, _params) do
    changeset = User.changeset(%User{})

    if Auth.signed_in?(conn) do
      conn
      |> put_flash(:error, "You're already logged in...")
      |> redirect(to: Routes.auction_path(conn, :index))
    else
      render(conn, "login.html", changeset: changeset)
    end
  end

  def verify(conn, %{"user" => %{"email" => email, "password" => password}}) do
    case Users.verify_login(email, password) do
      {:ok, user} ->
        conn
        |> put_session(:current_user_id, user.id)
        |> put_flash(:info, "You have successfully logged in!")
        |> redirect(to: Routes.auction_path(conn, :index))

      {:error, error} ->
        conn
        |> put_flash(:error, error)
        |> render("login.html", changeset: User.changeset(%User{}))
    end
  end
end

lib/renaissance_web/views/login_view.ex
defmodule RenaissanceWeb.LoginView do
  use RenaissanceWeb, :view
end

lib/renaissance_web/templates/login/login.html.eex
<div class="pageContent">
  <div class="pageGroup">
    <h1 class="lbl-group">Login</h1>
    <div class="form-text content-text">
      <%= link("Don't have an account? Register Here.", to: Routes.register_path(@conn, :new)) %>
    </div>

    <%= form_for @changeset, Routes.login_path(@conn, :verify), fn f -> %>
      <div class="form-section">
        <%= label f, :email, class: "lbl-form" %>
        <%= email_input f, :email, class: "txt-form", placeholder: "Email", required: true %>
        <%= error_tag f, :email %>
      </div>

      <div class="form-section">
        <%= label f, :password, class: "lbl-form" %>
        <%= password_input f, :password,  class: "txt-form", placeholder: "Password", required: true %>
        <%= error_tag f, :error %>
      </div>

      <div class="nav-container">
        <div class="nav-spacer"></div>
        <%= submit "Login" %>
      </div>
    <% end %>

  </div>
</div>